### PR TITLE
Correct component dependencies vs dev dependencies

### PR DESCRIPTION
**Pull request by jonterry-sans**

### CODE REVIEW

**Review by lbnlrnt — APPROVED** [review]

**Comment by lbnlrnt** [comment]
Would be great to have it! I'm not 100% sure if react and react-native cannot also just stay in dev dependencies as well

**Comment by jonterry-sans** [comment]
Since both `react` and `react-native` are explicitly used as dependencies in the component itself I would advise they be moved out of the dev dependencies. Realistically anyone using the component is using both of those, but it will at least enforce a usable version for downstream consumers.

**Comment by jonterry-sans** [comment]
I don't have merge access so if you're still interested in having this merged, you'll have to take care of that.

**Comment by mymai91** [comment]
Hi @jonterry-sans, Noted, and Thanks for your PR. I will take a look and feedback to you soon.
Thanks so much.

**Pull request closed without merging**
